### ISSUE TITLE
Ahouldn't define print-object for hash-table

### ISSUE THREAD

**Issue by Yehouda** [jsulmont/cl-transit#10]
https://github.com/jsulmont/cl-transit/blob/c5b5794287587471d8bbc7fd2789d7f37f7f7130/src/types.lisp#L84

**hash-table** is a system object, which is used in many places, and you shouldn't define methods for system geenric functions like **print-object** on them. 

LispWorks by default gives an error on this. You can get around by binding  [**\*handle-warn-on-redefinition\***](https://www.lispworks.com/documentation/lw80/lw/lw-lispworks-65.htm) around the definition, but the right fix is not to define it.

**Comment by jsulmont** [comment]
Good point thanks @Yehouda
